#! /usr/bin/env python

# Software License Agreement (BSD License)
#
# Copyright (c) 2013, Eric Perko
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the names of the authors nor the names of their
#    affiliated organizations may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import serial
import socket               # Import socket module
import rospy
import os                   #import libraries necessary for running the ifconfigg.sh file
import sys
import libnmea_navsat_driver.driver

if __name__ == '__main__':
    rospy.init_node('nmea_serial_driver')

    s = socket.socket()         # Create a socket object
    host = rospy.get_param('~host', 'reach.local')
    port = rospy.get_param('~port', 12346)
    #Reach = rospy.get_param('~reach', True)     #Check if mode of operation is the Reach GPS RTK
    sudoPassword = rospy.get_param('~sudoPassword', 'clearpath')
    ifconfiggpath = rospy.get_param('~ifconfiggpath', '/home/cear/pcl_ws/src/nmea_navsat_driver/scripts/ifconfigg.sh')

    s.connect((host, port))
    print "Device Connected"
    frame_id = libnmea_navsat_driver.driver.RosNMEADriver.get_frame_id()

    try:
        GPS = s.recv(1024)
        print "Message Received"
        driver = libnmea_navsat_driver.driver.RosNMEADriver()
        print "driver:", driver
        while not rospy.is_shutdown():
            GPS = s.recv(1024)
            data = GPS.strip()
	    
    	    split = data.split()
            print split
            data = split[0]
    	    for el in split:
    		  if 'GPGGA' in el:
    		      print "GPGGA found"
    		      data = el
    		      break
    		  elif 'RMC' in el:
    		      data = el           
        

            try:
                driver.add_sentence(data, frame_id)
                print "added sentence to driver"
            except ValueError as e:
                rospy.logwarn("Value error, likely due to missing fields in the NMEA message. Error was: %s. Please report this issue at github.com/ros-drivers/nmea_navsat_driver, including a bag file with the NMEA sentences that caused it." % e)

    except rospy.ROSInterruptException:
        GPS.close           #Close GPS socket when done
